// THIS FILE IS AUTOGENERATED, DO NOT MANUALLY EDIT

export const LAMBDA_LAYER_CATALOG = {
  versions: {
    extension: 99,
    dotnet: 25,
    java: 27,
    node: 142,
    python: 127,
    ruby: 30,
  },
  runtimes: {
    extension: {
      layers: {
        x86_64: 'Datadog-Extension',
        arm64: 'Datadog-Extension-ARM',
      },
    },
    dotnet6: {
      family: 'dotnet',
      layers: {
        x86_64: 'dd-trace-dotnet',
        arm64: 'dd-trace-dotnet-ARM',
      },
    },
    dotnet8: {
      family: 'dotnet',
      layers: {
        x86_64: 'dd-trace-dotnet',
        arm64: 'dd-trace-dotnet-ARM',
      },
    },
    dotnet10: {
      family: 'dotnet',
      layers: {
        x86_64: 'dd-trace-dotnet',
        arm64: 'dd-trace-dotnet-ARM',
      },
    },
    java11: {
      family: 'java',
      layers: {
        x86_64: 'dd-trace-java',
        arm64: 'dd-trace-java',
      },
    },
    java17: {
      family: 'java',
      layers: {
        x86_64: 'dd-trace-java',
        arm64: 'dd-trace-java',
      },
    },
    java21: {
      family: 'java',
      layers: {
        x86_64: 'dd-trace-java',
        arm64: 'dd-trace-java',
      },
    },
    java25: {
      family: 'java',
      layers: {
        x86_64: 'dd-trace-java',
        arm64: 'dd-trace-java',
      },
    },
    'java8.al2': {
      family: 'java',
      layers: {
        x86_64: 'dd-trace-java',
        arm64: 'dd-trace-java',
      },
    },
    'nodejs16.x': {
      family: 'node',
      layers: {
        x86_64: 'Datadog-Node16-x',
        arm64: 'Datadog-Node16-x',
      },
    },
    'nodejs18.x': {
      family: 'node',
      layers: {
        x86_64: 'Datadog-Node18-x',
        arm64: 'Datadog-Node18-x',
      },
    },
    'nodejs20.x': {
      family: 'node',
      layers: {
        x86_64: 'Datadog-Node20-x',
        arm64: 'Datadog-Node20-x',
      },
    },
    'nodejs22.x': {
      family: 'node',
      layers: {
        x86_64: 'Datadog-Node22-x',
        arm64: 'Datadog-Node22-x',
      },
    },
    'nodejs24.x': {
      family: 'node',
      layers: {
        x86_64: 'Datadog-Node24-x',
        arm64: 'Datadog-Node24-x',
      },
    },
    'provided.al2': {
      family: 'custom',
    },
    'provided.al2023': {
      family: 'custom',
    },
    'python3.8': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python38',
        arm64: 'Datadog-Python38-ARM',
      },
    },
    'python3.9': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python39',
        arm64: 'Datadog-Python39-ARM',
      },
    },
    'python3.10': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python310',
        arm64: 'Datadog-Python310-ARM',
      },
    },
    'python3.11': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python311',
        arm64: 'Datadog-Python311-ARM',
      },
    },
    'python3.12': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python312',
        arm64: 'Datadog-Python312-ARM',
      },
    },
    'python3.13': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python313',
        arm64: 'Datadog-Python313-ARM',
      },
    },
    'python3.14': {
      family: 'python',
      layers: {
        x86_64: 'Datadog-Python314',
        arm64: 'Datadog-Python314-ARM',
      },
    },
    'ruby3.2': {
      family: 'ruby',
      layers: {
        x86_64: 'Datadog-Ruby3-2',
        arm64: 'Datadog-Ruby3-2-ARM',
      },
    },
    'ruby3.3': {
      family: 'ruby',
      layers: {
        x86_64: 'Datadog-Ruby3-3',
        arm64: 'Datadog-Ruby3-3-ARM',
      },
    },
    'ruby3.4': {
      family: 'ruby',
      layers: {
        x86_64: 'Datadog-Ruby3-4',
        arm64: 'Datadog-Ruby3-4-ARM',
      },
    },
    'ruby4.0': {
      family: 'ruby',
      layers: {
        x86_64: 'Datadog-Ruby4-0',
        arm64: 'Datadog-Ruby4-0-ARM',
      },
    },
  },
} as const
