policy:
  - section:
      - id: [command]
        label:
          - name: 'ci-app'
            keys: ['junit', 'metric', 'tag', 'trace']
          - name: 'rum'
            keys: ['dsyms', 'flutter-symbols', 'react-native']
          - name: 'serverless'
            keys: ['lambda']
          - name: 'source-code-integration'
            keys: ['git-metadata', 'sourcemaps']
          - name: 'synthetics'
            keys: ['synthetics']
