stages:
  - build
  - release

build-docker-image:
  stage: build
  only: ['tags']
  when: manual
  allow_failure: false
  tags: ['arch:amd64']
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-gbi-focal
  script:
    - cd container
    - docker buildx build
      --platform linux/amd64,linux/arm64/v8
      --build-arg "VERSION=${CI_COMMIT_TAG}"
      --tag "registry.ddbuild.io/ci/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
      --push
      .

publish-docker-image:
  stage: release
  only: ['tags']
  needs: ['build-docker-image']
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: registry.ddbuild.io/ci/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    IMG_DESTINATIONS: ci:${CI_COMMIT_TAG},ci:latest
    IMG_SIGNING: 'false'
