stages:
  - build
  - release
  - catalog

build-docker-image:
  stage: build
  only: ['tags']
  when: manual
  allow_failure: false
  tags: ['arch:amd64']
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-gbi-focal
  script:
    - cd container
    - docker buildx build
      --platform linux/amd64,linux/arm64/v8
      --build-arg "VERSION=${CI_COMMIT_TAG}"
      --tag "registry.ddbuild.io/ci/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
      --push
      .

publish-docker-image:
  stage: release
  only: ['tags']
  needs: ['build-docker-image']
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: registry.ddbuild.io/ci/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    IMG_DESTINATIONS: ci:${CI_COMMIT_TAG},ci:latest
    IMG_SIGNING: 'false'

catalog-endpoints-generate:
  stage: catalog
  only: ['master']
  tags: ['arch:amd64']
  image: registry.ddbuild.io/images/mirror/node:22
  script:
    - yarn install --immutable
    - yarn catalog-endpoints
  artifacts:
    paths:
      - endpoints.csv
    expire_in: 1 hour

catalog-endpoints-upload:
  stage: catalog
  only: ['master']
  needs: ['catalog-endpoints-generate']
  tags: ['arch:amd64']
  image: registry.ddbuild.io/images/aws-cli:2.33.12
  id_tokens:
    CI_IDENTITIES_GITLAB_ID_TOKEN:
      aud: ci-identities
  variables:
    CI_IDENTITIES_CLIENT_VERSION: v0.6.6
  before_script:
    - aws s3 cp "s3://binaries-ddbuild-io-prod/ci-identities/ci-identities-gitlab-job-client/versions/${CI_IDENTITIES_CLIENT_VERSION}/ci-identities-gitlab-job-client-linux-amd64" "${CI_PROJECT_DIR}/ci-identities-gitlab-job-client"
    - chmod +x "${CI_PROJECT_DIR}/ci-identities-gitlab-job-client"
  script:
    - ${CI_PROJECT_DIR}/ci-identities-gitlab-job-client assume-role
    - aws s3 cp endpoints.csv s3://dd-datadog-ci/endpoints.csv
