compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# TODO: replace this with `2d` when we upgrade Yarn to >= 4.12
npmMinimalAgeGate: 2880  # 2 days in minutes.

yarnPath: .yarn/releases/yarn-4.10.3.cjs
