import {ENVIRONMENT_ENV_VAR, SERVICE_ENV_VAR, SITE_ENV_VAR} from '@datadog/datadog-ci-core/constants'

export const SKIP_MASKING_CLOUDRUN_ENV_VARS = new Set([
  SITE_ENV_VAR,
  SERVICE_ENV_VAR,
  ENVIRONMENT_ENV_VAR,
  'NODE_OPTIONS',
  'DD_TRACE_PROPAGATION_STYLE',
  'DD_SOURCE',
  'DD_TAGS',
  'DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT',
  'DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT',
  'GCP_PROJECT_ID',
  'DD_VERSION',
  'DD_AGENT_HOST',
  'DD_LOG_LEVEL',
  'GCP_PUBSUB_PROJECT_ID',
  'GCP_PUBSUB_SUBSCRIBER_ID',
])
