import {ENVIRONMENT_ENV_VAR, SERVICE_ENV_VAR, SITE_ENV_VAR} from '../../constants'

const NODE_OPTIONS_ENV_VAR = 'NODE_OPTIONS'
const DD_TRACE_PROPAGATION_STYLE_ENV_VAR = 'DD_TRACE_PROPAGATION_STYLE'
const DD_SOURCE_ENV_VAR = 'DD_SOURCE'
const DD_TAGS_ENV_VAR = 'DD_TAGS'
const DD_OLTP_HTTPS_ENV_VAR = 'DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT'
const DD_OLTP_GRPC_ENV_VAR = 'DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT'

export const SKIP_MASKING_CLOUDRUN_ENV_VARS = new Set([
  SITE_ENV_VAR,
  SERVICE_ENV_VAR,
  ENVIRONMENT_ENV_VAR,
  NODE_OPTIONS_ENV_VAR,
  DD_TRACE_PROPAGATION_STYLE_ENV_VAR,
  DD_SOURCE_ENV_VAR,
  DD_TAGS_ENV_VAR,
  DD_OLTP_HTTPS_ENV_VAR,
  DD_OLTP_GRPC_ENV_VAR,
])
