name: Publish package on NPM
on:
  release:
    types: [prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.24.1'
      - run: |
          # Isolate the tag and exit if none found
          IFS='-' read -ra ARR_TAG <<< $TAG
          if ((${#ARR_TAG[@]} <= 1)); then echo "Missing channel in given tag '$TAG'. Should be in the format '<version>-<channel>'" && exit 1; fi
          TAG_TO_PUBLISH=${ARR_TAG[${#ARR_TAG[@]} - 1]}

          # Publish on npm in the correct channel
          yarn
          echo "Publishing on $TAG_TO_PUBLISH channel."
          yarn publish --tag=$TAG_TO_PUBLISH
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
